services:
  - type: web
    name: obsidian-marketplace-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
